[dispatcher]
id = "dispatcher"
socket_file_mode = "0770"

application_socket = "/dev/shm/dispatcher/default.sock"

[log.console]
level = "info"

# Optionally expose metrics and other local inspection endpoints.
# [metrics]
# prometheus = "[127.0.0.1]:30441"
